export type ShopSlot =
  | "hat"
  | "top"
  | "bottom"
  | "shoes"
  | "accessory"
  | "dress"
  | "earrings"
  | "necklace"
  | "bracelet"
  | "hairClip"
  | "earPiercing"
  | "facePiercing"
  | "ears";

export type ShopItem = {
  id: string;
  name: string;
  slot: ShopSlot;
  price: number;
  emoji: string; // small icon for the catalog tile
  /**
   * Color used when rendering this piece on the paper-doll. Optional —
   * accessory/hat pieces sometimes render as emoji overlays instead.
   */
  color?: string;
  /** When set, the doll renders this emoji in the slot instead of a shape. */
  overlayEmoji?: string;
  /** Themed-set tag: which quest-giver this belongs to (or "basic"/"premium"). */
  set: "basic" | "willow" | "professor-hoot" | "pip" | "mossback" | "clover" | "premium";
  description: string;
};

/** All items the shop can sell. The id is what gets stored in dressup. */
export const SHOP_ITEMS: ShopItem[] = [
  // -- BASICS ---------------------------------------------------------------
  {
    id: "basic-tee-moss",
    name: "Moss Tee",
    slot: "top",
    price: 0,
    emoji: "👕",
    color: "#5b8a3a",
    set: "basic",
    description: "A soft cotton tee the color of fresh moss.",
  },
  {
    id: "basic-tee-bloom",
    name: "Bloom Tee",
    slot: "top",
    price: 0,
    emoji: "👕",
    color: "#d97a8a",
    set: "basic",
    description: "A warm pink tee for sunny mornings.",
  },
  {
    id: "basic-jacket",
    name: "Field Jacket",
    slot: "top",
    price: 80,
    emoji: "🧥",
    color: "#7a6240",
    set: "basic",
    description: "Lots of pockets for pebbles and feathers.",
  },
  {
    id: "basic-sweater",
    name: "Knit Sweater",
    slot: "top",
    price: 70,
    emoji: "🧶",
    color: "#3a6ea5",
    set: "basic",
    description: "Hand-knit, slightly itchy in the best way.",
  },
  {
    id: "basic-raincoat",
    name: "Yellow Raincoat",
    slot: "top",
    price: 90,
    emoji: "🧥",
    color: "#e0b840",
    set: "basic",
    description: "Bright as a buttercup, dry as a bone.",
  },
  {
    id: "basic-flannel",
    name: "Flannel Shirt",
    slot: "top",
    price: 55,
    emoji: "👔",
    color: "#a04848",
    set: "basic",
    description: "Red plaid. Smells faintly of woodsmoke.",
  },
  {
    id: "basic-jeans",
    name: "Walking Jeans",
    slot: "bottom",
    price: 0,
    emoji: "👖",
    color: "#3a4f78",
    set: "basic",
    description: "Tough denim that survives bramble paths.",
  },
  {
    id: "basic-shorts",
    name: "Meadow Shorts",
    slot: "bottom",
    price: 30,
    emoji: "🩳",
    color: "#a3884f",
    set: "basic",
    description: "Breezy shorts for warm wandering.",
  },
  {
    id: "basic-cargo",
    name: "Cargo Trousers",
    slot: "bottom",
    price: 60,
    emoji: "👖",
    color: "#5b6b3a",
    set: "basic",
    description: "Six pockets — one for each pebble.",
  },
  {
    id: "basic-overalls",
    name: "Garden Overalls",
    slot: "bottom",
    price: 75,
    emoji: "👖",
    color: "#3a5a78",
    set: "basic",
    description: "For digging, kneeling, and napping in.",
  },
  {
    id: "basic-boots",
    name: "Hiking Boots",
    slot: "shoes",
    price: 60,
    emoji: "🥾",
    color: "#5b3a1f",
    set: "basic",
    description: "Broken-in boots, ready for any trail.",
  },
  {
    id: "basic-sneakers",
    name: "Soft Sneakers",
    slot: "shoes",
    price: 0,
    emoji: "👟",
    color: "#dcdcdc",
    set: "basic",
    description: "For a gentler kind of expedition.",
  },
  {
    id: "basic-sandals",
    name: "Brook Sandals",
    slot: "shoes",
    price: 35,
    emoji: "🩴",
    color: "#8a6240",
    set: "basic",
    description: "Wade through streams, dry in seconds.",
  },
  {
    id: "basic-wellies",
    name: "Rain Wellies",
    slot: "shoes",
    price: 55,
    emoji: "🥾",
    color: "#3a6a78",
    set: "basic",
    description: "Puddle-ready, mud-proof.",
  },
  {
    id: "basic-crop-blush",
    name: "Blush Crop Top",
    slot: "top",
    price: 45,
    emoji: "👚",
    color: "#e889a8",
    set: "basic",
    description: "A cute cropped tee with soft sleeves.",
  },
  {
    id: "basic-tank-sky",
    name: "Sky Tank Top",
    slot: "top",
    price: 35,
    emoji: "🎽",
    color: "#69a7d8",
    set: "basic",
    description: "Simple, bright, and easy to layer.",
  },
  {
    id: "basic-longsleeve",
    name: "Long Sleeve Top",
    slot: "top",
    price: 55,
    emoji: "👕",
    color: "#8a6fd8",
    set: "basic",
    description: "A neat long-sleeve top for cooler days.",
  },
  {
    id: "basic-pleat-skirt",
    name: "Pleated Skirt",
    slot: "bottom",
    price: 45,
    emoji: "👗",
    color: "#d86f9b",
    set: "basic",
    description: "A soft little skirt that twirls nicely.",
  },
  {
    id: "basic-denim-skirt",
    name: "Denim Skirt",
    slot: "bottom",
    price: 50,
    emoji: "👗",
    color: "#4b6f9f",
    set: "basic",
    description: "A classic denim skirt for everyday outfits.",
  },
  {
    id: "basic-leggings",
    name: "Cozy Leggings",
    slot: "bottom",
    price: 40,
    emoji: "👖",
    color: "#343044",
    set: "basic",
    description: "Soft leggings for running around.",
  },
  {
    id: "basic-slippers",
    name: "Cloud Slippers",
    slot: "shoes",
    price: 30,
    emoji: "🩴",
    color: "#f0b6c8",
    set: "basic",
    description: "Comfy slippers with a soft rounded shape.",
  },
  {
    id: "basic-maryjanes",
    name: "Mary Janes",
    slot: "shoes",
    price: 50,
    emoji: "👞",
    color: "#2f2a34",
    set: "basic",
    description: "Neat little shoes for dressy outfits.",
  },
  {
    id: "basic-canvas-high",
    name: "High Sneakers",
    slot: "shoes",
    price: 60,
    emoji: "👟",
    color: "#f2f2f2",
    set: "basic",
    description: "Chunky high-top sneakers.",
  },
  {
    id: "basic-pinafore",
    name: "Pinafore Dress",
    slot: "dress",
    price: 0,
    emoji: "👗",
    color: "#e8a0b8",
    set: "basic",
    description: "A simple cute dress with a soft skirt.",
  },
  {
    id: "basic-party-dress",
    name: "Party Dress",
    slot: "dress",
    price: 90,
    emoji: "👗",
    color: "#b98cf0",
    set: "basic",
    description: "A puffy little dress for celebrations.",
  },
  {
    id: "dress-floral-pink",
    name: "Floral Pink Dress",
    slot: "dress",
    price: 80,
    emoji: "👗",
    color: "#f7c8d4",
    set: "basic",
    description: "Soft pink A-line with a sweet bow at the waist.",
  },
  {
    id: "dress-lavender-party",
    name: "Lavender Party Dress",
    slot: "dress",
    price: 110,
    emoji: "👗",
    color: "#c8a8e8",
    set: "basic",
    description: "Lace-collared lavender dress with puff sleeves.",
  },
  {
    id: "dress-pinafore-pink",
    name: "Pink Pinafore",
    slot: "dress",
    price: 70,
    emoji: "👗",
    color: "#f5d6dc",
    set: "basic",
    description: "White pinafore over pink, with a blue bow pocket.",
  },
  {
    id: "dress-sailor-blue",
    name: "Sailor Dress",
    slot: "dress",
    price: 95,
    emoji: "⚓",
    color: "#a8d4f0",
    set: "basic",
    description: "Blue pleated sailor dress with a red kerchief.",
  },
  {
    id: "dress-sweater-mint",
    name: "Bear Sweater Dress",
    slot: "dress",
    price: 85,
    emoji: "🧸",
    color: "#cfeacd",
    set: "basic",
    description: "Cozy mint sweater dress with a bear face.",
  },
  {
    id: "dress-sundress-black",
    name: "Black Floral Sundress",
    slot: "dress",
    price: 100,
    emoji: "🌸",
    color: "#2a2530",
    set: "basic",
    description: "Charcoal sundress scattered with little white flowers.",
  },
  {
    id: "basic-cap",
    name: "Canvas Cap",
    slot: "hat",
    price: 25,
    emoji: "🧢",
    color: "#5b6b3a",
    set: "basic",
    description: "Keeps the sun off your sketches.",
  },
  {
    id: "basic-beanie",
    name: "Wool Beanie",
    slot: "hat",
    price: 30,
    emoji: "🧶",
    color: "#5b3a78",
    set: "basic",
    description: "For chilly dawn starts.",
  },
  {
    id: "basic-sunhat",
    name: "Straw Sunhat",
    slot: "hat",
    price: 45,
    emoji: "👒",
    color: "#d8b87a",
    set: "basic",
    description: "Wide-brimmed and breezy.",
  },
  {
    id: "basic-bandana",
    name: "Trail Bandana",
    slot: "hat",
    price: 20,
    emoji: "🧣",
    color: "#a04848",
    set: "basic",
    description: "Tied above the brow, like a proper scout.",
  },
  {
    id: "basic-scarf",
    name: "Cozy Scarf",
    slot: "accessory",
    price: 0,
    emoji: "🧣",
    overlayEmoji: "🧣",
    set: "basic",
    description: "For brisk dawn walks.",
  },
  {
    id: "basic-glasses",
    name: "Round Glasses",
    slot: "accessory",
    price: 0,
    emoji: "👓",
    overlayEmoji: "👓",
    set: "basic",
    description: "Spot the smallest insects.",
  },
  {
    id: "basic-binoculars",
    name: "Pocket Binoculars",
    slot: "accessory",
    price: 60,
    emoji: "🔭",
    overlayEmoji: "🔭",
    set: "basic",
    description: "Bring distant birds politely closer.",
  },
  {
    id: "basic-backpack",
    name: "Canvas Backpack",
    slot: "accessory",
    price: 70,
    emoji: "🎒",
    overlayEmoji: "🎒",
    set: "basic",
    description: "Holds your notebook, snacks, and one small mystery.",
  },
  {
    id: "basic-compass",
    name: "Brass Compass",
    slot: "accessory",
    price: 0,
    emoji: "🧭",
    overlayEmoji: "🧭",
    set: "basic",
    description: "Always points home — eventually.",
  },

  // -- WILLOW (witch) -------------------------------------------------------
  {
    id: "willow-hat",
    name: "Hedge Witch Hat",
    slot: "hat",
    price: 120,
    emoji: "🎩",
    overlayEmoji: "🧙‍♀️",
    set: "willow",
    description: "Pointed and patched, smelling faintly of thyme.",
  },
  {
    id: "willow-cloak",
    name: "Herbwitch Cloak",
    slot: "top",
    price: 150,
    emoji: "🥼",
    color: "#3a2a4f",
    set: "willow",
    description: "Deep purple with a hidden pocket of dried lavender.",
  },
  {
    id: "willow-skirt",
    name: "Bramble Skirt",
    slot: "bottom",
    price: 110,
    emoji: "👗",
    color: "#4f2a3a",
    set: "willow",
    description: "Long, dark, and patched with embroidered ferns.",
  },
  {
    id: "willow-amulet",
    name: "Moonstone Amulet",
    slot: "accessory",
    price: 130,
    emoji: "🌙",
    overlayEmoji: "🌙",
    set: "willow",
    description: "Glows faintly when you sketch under moonlight.",
  },
  {
    id: "willow-boots",
    name: "Witch's Boots",
    slot: "shoes",
    price: 120,
    emoji: "🥾",
    color: "#2a1f3a",
    set: "willow",
    description: "Buckled, weathered, perfect for hedge-hopping.",
  },

  // -- PROFESSOR HOOT (owl) -------------------------------------------------
  {
    id: "hoot-cloak",
    name: "Feather Cloak",
    slot: "top",
    price: 150,
    emoji: "🪶",
    color: "#6b5a3a",
    set: "professor-hoot",
    description: "Lined with soft owl-down. Whispers when you turn.",
  },
  {
    id: "hoot-glasses",
    name: "Sage Spectacles",
    slot: "accessory",
    price: 80,
    emoji: "👓",
    overlayEmoji: "🤓",
    set: "professor-hoot",
    description: "Lets you read riddles in tree bark.",
  },
  {
    id: "hoot-cap",
    name: "Scholar's Cap",
    slot: "hat",
    price: 100,
    emoji: "🎓",
    overlayEmoji: "🎓",
    set: "professor-hoot",
    description: "Tasselled. Rather dignified.",
  },
  {
    id: "hoot-trousers",
    name: "Tweed Trousers",
    slot: "bottom",
    price: 95,
    emoji: "👖",
    color: "#7a6a4a",
    set: "professor-hoot",
    description: "Pressed and patched at both knees.",
  },
  {
    id: "hoot-loafers",
    name: "Library Loafers",
    slot: "shoes",
    price: 85,
    emoji: "👞",
    color: "#5b3a2a",
    set: "professor-hoot",
    description: "Quiet enough not to wake the books.",
  },

  // -- PIP (fox) ------------------------------------------------------------
  {
    id: "pip-scarf",
    name: "Fox-Tail Scarf",
    slot: "accessory",
    price: 90,
    emoji: "🦊",
    overlayEmoji: "🦊",
    set: "pip",
    description: "Bushy and bright. Pip insists it's not from his tail.",
  },
  {
    id: "pip-sneakers",
    name: "Scout Sneakers",
    slot: "shoes",
    price: 100,
    emoji: "👟",
    color: "#c25a2a",
    set: "pip",
    description: "Light enough to keep up with Pip. Almost.",
  },
  {
    id: "pip-hoodie",
    name: "Russet Hoodie",
    slot: "top",
    price: 110,
    emoji: "🧥",
    color: "#c25a2a",
    set: "pip",
    description: "Warm orange, perfect for blending into autumn.",
  },
  {
    id: "pip-cap",
    name: "Fox-Ear Cap",
    slot: "hat",
    price: 95,
    emoji: "🦊",
    overlayEmoji: "🦊",
    set: "pip",
    description: "Two perky ears, one mischievous grin.",
  },
  {
    id: "pip-shorts",
    name: "Trail Shorts",
    slot: "bottom",
    price: 65,
    emoji: "🩳",
    color: "#a04420",
    set: "pip",
    description: "Quick-dry, very fast on slopes.",
  },

  // -- MOSSBACK (toad) ------------------------------------------------------
  {
    id: "mossback-hat",
    name: "Lily-Pad Hat",
    slot: "hat",
    price: 110,
    emoji: "🍃",
    overlayEmoji: "🪷",
    set: "mossback",
    description: "A wide green disc that Mossback definitely didn't sit on first.",
  },
  {
    id: "mossback-boots",
    name: "Pond Wellies",
    slot: "shoes",
    price: 90,
    emoji: "🥾",
    color: "#3a5a3a",
    set: "mossback",
    description: "Splash through any puddle, dignified.",
  },
  {
    id: "mossback-poncho",
    name: "Reed Poncho",
    slot: "top",
    price: 130,
    emoji: "🥽",
    color: "#4a6a3a",
    set: "mossback",
    description: "Woven from pond reeds. Surprisingly waterproof.",
  },
  {
    id: "mossback-pants",
    name: "Marsh Trousers",
    slot: "bottom",
    price: 80,
    emoji: "👖",
    color: "#3a4a2a",
    set: "mossback",
    description: "Mottled green — disappears in the reeds.",
  },
  {
    id: "mossback-amulet",
    name: "Pond-Stone Pendant",
    slot: "accessory",
    price: 70,
    emoji: "🪨",
    overlayEmoji: "🪨",
    set: "mossback",
    description: "Smooth and cool. Hums quietly near water.",
  },

  // -- CLOVER (bunny) -------------------------------------------------------
  {
    id: "clover-flower",
    name: "Daisy Crown",
    slot: "hat",
    price: 70,
    emoji: "🌼",
    overlayEmoji: "🌼",
    set: "clover",
    description: "Woven by Clover at sunrise. Smells like meadow.",
  },
  {
    id: "clover-dress",
    name: "Sunshine Smock",
    slot: "dress",
    price: 110,
    emoji: "👗",
    color: "#e0c75a",
    set: "clover",
    description: "The color of a four-leaf-clover wish.",
  },
  {
    id: "clover-cardigan",
    name: "Petal Cardigan",
    slot: "top",
    price: 95,
    emoji: "🧶",
    color: "#e8a8c0",
    set: "clover",
    description: "Soft pink, with tiny embroidered clovers.",
  },
  {
    id: "clover-skirt",
    name: "Meadow Skirt",
    slot: "bottom",
    price: 75,
    emoji: "👗",
    color: "#9ac84a",
    set: "clover",
    description: "Twirly and grass-stained — the good kind.",
  },
  {
    id: "clover-shoes",
    name: "Hop-Along Shoes",
    slot: "shoes",
    price: 65,
    emoji: "👟",
    color: "#f0d8e8",
    set: "clover",
    description: "So bouncy you'll forget you have feet.",
  },
  {
    id: "clover-charm",
    name: "Four-Leaf Charm",
    slot: "accessory",
    price: 100,
    emoji: "🍀",
    overlayEmoji: "🍀",
    set: "clover",
    description: "Clover's lucky favourite. Don't lose it.",
  },

  // -- PREMIUM: jewelry -----------------------------------------------------
  {
    id: "prem-earrings-gold",
    name: "Gold Hoops",
    slot: "earrings",
    price: 180,
    emoji: "👂",
    overlayEmoji: "✨",
    color: "#e0b840",
    set: "premium",
    description: "Polished gold hoops that catch the light.",
  },
  {
    id: "prem-earrings-pearl",
    name: "Pearl Studs",
    slot: "earrings",
    price: 150,
    emoji: "🤍",
    color: "#f0e6d8",
    set: "premium",
    description: "Tiny pearls. Quietly elegant.",
  },
  {
    id: "prem-earrings-stars",
    name: "Star Drops",
    slot: "earrings",
    price: 200,
    emoji: "⭐",
    color: "#e8c850",
    set: "premium",
    description: "Little stars that swing when you walk.",
  },
  {
    id: "prem-necklace-heart",
    name: "Heart Pendant",
    slot: "necklace",
    price: 220,
    emoji: "💗",
    color: "#e85a8a",
    set: "premium",
    description: "A delicate gold chain with a heart charm.",
  },
  {
    id: "prem-necklace-moon",
    name: "Crescent Necklace",
    slot: "necklace",
    price: 240,
    emoji: "🌙",
    color: "#d8d8e8",
    set: "premium",
    description: "Silver crescent on a fine chain.",
  },
  {
    id: "prem-bracelet-beads",
    name: "Bead Bracelet",
    slot: "bracelet",
    price: 120,
    emoji: "📿",
    color: "#a04848",
    set: "premium",
    description: "Hand-strung wooden beads.",
  },
  {
    id: "prem-bracelet-charm",
    name: "Charm Bracelet",
    slot: "bracelet",
    price: 200,
    emoji: "🔗",
    color: "#c0a040",
    set: "premium",
    description: "Tiny charms that jingle softly.",
  },

  // -- PREMIUM: hair accessories --------------------------------------------
  {
    id: "prem-clip-bow",
    name: "Velvet Bow",
    slot: "hairClip",
    price: 140,
    emoji: "🎀",
    color: "#c83a5a",
    set: "premium",
    description: "A deep red bow for tucking into hair.",
  },
  {
    id: "prem-clip-flower",
    name: "Flower Clip",
    slot: "hairClip",
    price: 130,
    emoji: "🌸",
    color: "#f0a8c0",
    set: "premium",
    description: "A blossom clip — never wilts.",
  },
  {
    id: "prem-clip-pearl",
    name: "Pearl Pin",
    slot: "hairClip",
    price: 160,
    emoji: "✨",
    color: "#f0e6d8",
    set: "premium",
    description: "Pearl-tipped hairpin.",
  },
  {
    id: "prem-clip-star",
    name: "Star Hair Clip",
    slot: "hairClip",
    price: 120,
    emoji: "⭐",
    color: "#e8c850",
    set: "premium",
    description: "A tiny golden star clip that twinkles in sunlight.",
  },
  {
    id: "prem-clip-butterfly",
    name: "Butterfly Clip",
    slot: "hairClip",
    price: 140,
    emoji: "🦋",
    color: "#8ac8f0",
    set: "premium",
    description: "A pale-blue butterfly that perches in your hair.",
  },
  {
    id: "prem-clip-heart",
    name: "Heart Clip",
    slot: "hairClip",
    price: 110,
    emoji: "💗",
    color: "#f0a8c0",
    set: "premium",
    description: "A sweet little heart-shaped barrette.",
  },
  {
    id: "prem-clip-leaf",
    name: "Leaf Clip",
    slot: "hairClip",
    price: 100,
    emoji: "🍃",
    color: "#9ac84a",
    set: "basic",
    description: "A pressed-leaf clip for woodland wanderers.",
  },
  {
    id: "prem-clip-mushroom",
    name: "Mushroom Clip",
    slot: "hairClip",
    price: 130,
    emoji: "🍄",
    color: "#c84a4a",
    set: "basic",
    description: "A red-capped mushroom clip with tiny white spots.",
  },
  {
    id: "prem-clip-moon",
    name: "Crescent Clip",
    slot: "hairClip",
    price: 150,
    emoji: "🌙",
    color: "#d8d8e8",
    set: "premium",
    description: "A silver crescent moon for dreamy days.",
  },

  // -- PREMIUM: piercings ---------------------------------------------------
  {
    id: "prem-ear-stud",
    name: "Tiny Ear Stud",
    slot: "earPiercing",
    price: 80,
    emoji: "💎",
    color: "#a8d8f0",
    set: "premium",
    description: "A single small stud, second hole.",
  },
  {
    id: "prem-ear-cuff",
    name: "Silver Ear Cuff",
    slot: "earPiercing",
    price: 140,
    emoji: "🪙",
    color: "#c0c0d0",
    set: "premium",
    description: "Wraps around the upper ear.",
  },
  {
    id: "prem-face-nose",
    name: "Nose Stud",
    slot: "facePiercing",
    price: 110,
    emoji: "💠",
    color: "#e0e0f0",
    set: "premium",
    description: "A delicate sparkle at the side of the nose.",
  },
  {
    id: "prem-face-lip",
    name: "Lip Ring",
    slot: "facePiercing",
    price: 130,
    emoji: "⚪",
    color: "#c0c0c0",
    set: "premium",
    description: "A small ring on the lower lip.",
  },
  {
    id: "prem-face-eyebrow",
    name: "Brow Bar",
    slot: "facePiercing",
    price: 130,
    emoji: "▫️",
    color: "#a0a0b0",
    set: "premium",
    description: "A small bar through the brow.",
  },

  // -- PREMIUM: ear extras (hearing aids / earpods / headphones) -----------
  {
    id: "prem-ears-hearing",
    name: "Hearing Aid",
    slot: "ears",
    price: 0,
    emoji: "🦻",
    color: "#e8d8c8",
    set: "basic",
    description: "A subtle behind-the-ear hearing aid.",
  },
  {
    id: "prem-ears-pods",
    name: "Wireless Earpods",
    slot: "ears",
    price: 200,
    emoji: "🎧",
    color: "#f0f0f0",
    set: "premium",
    description: "Tiny wireless buds.",
  },
  {
    id: "prem-ears-headphones",
    name: "Big Headphones",
    slot: "ears",
    price: 280,
    emoji: "🎧",
    color: "#3a3a4a",
    set: "premium",
    description: "Cozy over-ear cans.",
  },

  // -- PREMIUM: dresses (one-piece) -----------------------------------------
  {
    id: "prem-dress-princess",
    name: "Princess Gown",
    slot: "dress",
    price: 360,
    emoji: "👗",
    color: "#c78cf2",
    set: "premium",
    description: "A full princess gown with a sparkly skirt.",
  },
  {
    id: "prem-dress-rose",
    name: "Rose Ballgown",
    slot: "dress",
    price: 340,
    emoji: "👗",
    color: "#e874a2",
    set: "premium",
    description: "A rounded rose-pink ballgown.",
  },
  {
    id: "prem-dress-tutu",
    name: "Ribbon Tutu",
    slot: "dress",
    price: 260,
    emoji: "👗",
    color: "#f0a8d8",
    set: "premium",
    description: "A layered tutu dress with a ribbon waist.",
  },
  {
    id: "prem-shoes-sparkle",
    name: "Sparkle Sneakers",
    slot: "shoes",
    price: 170,
    emoji: "👟",
    color: "#d8d8f0",
    set: "premium",
    description: "Sneakers with tiny star shine.",
  },
  {
    id: "prem-shoes-bow",
    name: "Bow Sandals",
    slot: "shoes",
    price: 150,
    emoji: "🩴",
    color: "#e8a0b8",
    set: "premium",
    description: "Soft sandals with little bows.",
  },
  {
    id: "prem-dress-floral",
    name: "Floral Sundress",
    slot: "dress",
    price: 220,
    emoji: "👗",
    color: "#e89ab8",
    set: "premium",
    description: "Pink with tiny embroidered daisies.",
  },
  {
    id: "prem-dress-night",
    name: "Starlight Gown",
    slot: "dress",
    price: 320,
    emoji: "👗",
    color: "#3a3a78",
    set: "premium",
    description: "Deep navy with a sparkle of stars.",
  },
  {
    id: "prem-dress-meadow",
    name: "Meadow Dress",
    slot: "dress",
    price: 200,
    emoji: "👗",
    color: "#7ab050",
    set: "premium",
    description: "Soft green, twirls beautifully.",
  },
];

export function getItemById(id: string | null | undefined): ShopItem | undefined {
  if (!id) return undefined;
  return SHOP_ITEMS.find((i) => i.id === id);
}

export const COINS_PER_ENTRY = 15;
